### PR TITLE
Create settingsparse.go

### PR DESCRIPTION
**Pull request by 1proprogrammerchant**
parse for the setting json into Go code

### CODE REVIEW

**Comment by freddydk** [comment]
We don't take contributions to the template repositories

**Comment by 1proprogrammerchant** [comment]
dang where can I contribute then

**Comment by freddydk** [comment]
Well, why would you mix .go code with the Business Central DevOps template - I don't understand that.

**Comment by 1proprogrammerchant** [comment]
I only did it because its using AL-Go I was confused that's my fault

**Pull request closed without merging**
